version: '3'
services:
  caddy:
    image: caddy:2.4.2
    restart: unless-stopped
    volumes:
      - ./conf/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "54120:80"
  php:
    build: .
    restart: unless-stopped
    working_dir: /srv
    volumes:
      - ./src:/srv