version: "3.0"
services:
  rctf-mysql80:
    image: mysql:8.0.26
    user: mysql:mysql
    command: --default-authentication-plugin=mysql_native_password --max-connections=1024
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: "**********************************"
      MYSQL_DATABASE: rctf2021
    restart: always
    container_name: rctf-mysql80
